name: fakeplayer
version: '${revision}'
main: io.github.hello09x.fakeplayer.core.Main
api-version: '26.2' #26.2 is the chosen support floor
author: hxrry
website: 'https://github.com/hxrry27/fakeplayer'

softdepend:
  - PlaceholderAPI

permissions:
  fakeplayer.command:
    description: 'Use the /player command'
    default: op
  fakeplayer.config.replenish:
    description: 'Configure fake players to auto-replenish'
  fakeplayer.config.replenish.chest:
    description: 'Configure fake players to replenish from a nearby chest'
  fakeplayer.config.autofish:
    description: 'Configure fake players to auto-fish'
  fakeplayer.config.autosleep:
    description: 'Configure fake players to auto-sleep'
